# Railway service config for OptiMeal API
# Docs: https://docs.railway.app/deploy/config

[build]
# Use Nixpacks to detect Python and install requirements.txt
builder = "NIXPACKS"

[deploy]
# FastAPI entrypoint
startCommand = "uvicorn src.main:app --host 0.0.0.0 --port ${PORT}"

[env]
PYTHON_VERSION = "3.11"
ENVIRONMENT = "production"
# Set these in Railway → Variables (do NOT commit secrets):
# DATABASE_URL = "postgresql://..."
# SECRET_KEY = "..."
# ACCESS_TOKEN_EXPIRE_MINUTES = "10080"
# GEMINI_API_KEY = "..."
# OCR_CONFIDENCE_THRESHOLD = "0.6"
# PADDLEOCR_LANG = "en"